export const GETTING_CONVERSATION_LIST = "GETTING_CONVERSATION_LIST";
export const GET_CONVERSATION_LIST = "GET_CONVERSATION_LIST";
export const SET_CONVERSATION_LIST = "SET_CONVERSATION_LIST";
export const SET_CONVERSATION_ERROR = "SET_CONVERSATION_ERROR";

export const getConversationList = () => {
  return { type: GET_CONVERSATION_LIST };
};
